name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate pacman
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: IrvingTKNG

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "update pacman graph" || exit 0
          git push origin HEAD:output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
